// Copyright (c) 2012 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

//do not include in .h file alone
//#pragma once


//too ugly...
BEGIN_NOTIFICATION_TYPE_MACRO
  HEAD_NOTIFICATION_TYPE_MACRO
  //phone 
  //自动模式和手动模式两个界面，但只有一个在显示，要把信息给到显示者=
  ITEM_NOTIFICATION_TYPE_MACRO(NOTIFICATION_PHONE_, TRANSFER_APK_UPDATE_INFO)
  ITEM_NOTIFICATION_TYPE_MACRO(NOTIFICATION_PHONE_, TRANSFER_INSTALL_APK_DIGEST)
  //ITEM_NOTIFICATION_TYPE_MACRO(NOTIFICATION_PHONE_, TRANSFER_APK_UPDATE_INFO)


  //ctp

  //tu
  ITEM_NOTIFICATION_TYPE_MACRO(NOTIFICATION_CTP_, TU_CREATED)
  ITEM_NOTIFICATION_TYPE_MACRO(NOTIFICATION_CTP_, TU_DESTROYED)


  //tsm
  // ITEM_NOTIFICATION_TYPE_MACRO(NOTIFICATION_CTP_, TSM_CONNECTED)
  // ITEM_NOTIFICATION_TYPE_MACRO(NOTIFICATION_CTP_, TSM_DISCONNECT)
  // //用户广播信息给ui显示=
  // ITEM_NOTIFICATION_TYPE_MACRO(NOTIFICATION_CTP_, TSM_LOGIN_RSP)
  // //用于广播登录成功，模块处理相关逻辑，比如发SettlementInfoConfirm=
  // ITEM_NOTIFICATION_TYPE_MACRO(NOTIFICATION_CTP_, TSM_LOGIN_SUCCESS)
  // ITEM_NOTIFICATION_TYPE_MACRO(NOTIFICATION_CTP_, TSM_LOGOUT_RSP)
  // ITEM_NOTIFICATION_TYPE_MACRO(NOTIFICATION_CTP_, TSM_STATE_CHANGE)
  // ITEM_NOTIFICATION_TYPE_MACRO(NOTIFICATION_CTP_, TSM_STATE_CHANGE_DEAL)
  // ITEM_NOTIFICATION_TYPE_MACRO(NOTIFICATION_CTP_, TSM_STATE_CHANGE_NODEAL)
  // //ITEM_NOTIFICATION_TYPE_MACRO(NOTIFICATION_CTP_, TSM_NETWORK)
  // ITEM_NOTIFICATION_TYPE_MACRO(NOTIFICATION_CTP_, TSM_TIMER)

  // //msm
  // ITEM_NOTIFICATION_TYPE_MACRO(NOTIFICATION_CTP_, MSM_STATE_CHANGE)
  // ITEM_NOTIFICATION_TYPE_MACRO(NOTIFICATION_CTP_, MSM_TIMER)
  // ITEM_NOTIFICATION_TYPE_MACRO(NOTIFICATION_CTP_, MSM_STATE_CHANGE_NODEAL)
  // ITEM_NOTIFICATION_TYPE_MACRO(NOTIFICATION_CTP_, MSM_CONNECTED)
  // ITEM_NOTIFICATION_TYPE_MACRO(NOTIFICATION_CTP_, MSM_DISCONNECT)



  ITEM_NOTIFICATION_TYPE_MACRO(NOTIFICATION_CTP_, NETWORK_ERROR)


  //dc
  ITEM_NOTIFICATION_TYPE_MACRO(NOTIFICATION_CTP_, DC_RECEIVE_DATA)
  ITEM_NOTIFICATION_TYPE_MACRO(NOTIFICATION_CTP_, DC_RECEIVE_POSITION)
  ITEM_NOTIFICATION_TYPE_MACRO(NOTIFICATION_CTP_, DC_RECEIVE_POSITION_TEST_SERVER_FAULT_TOLERANCE)
  ITEM_NOTIFICATION_TYPE_MACRO(NOTIFICATION_CTP_, DC_RECEIVE_CASH)
  ITEM_NOTIFICATION_TYPE_MACRO(NOTIFICATION_CTP_, DC_RECEIVE_POSITION_SHOW)
  ITEM_NOTIFICATION_TYPE_MACRO(NOTIFICATION_CTP_, DC_RECEIVE_CASH_SHOW)

  //mqdc
  ITEM_NOTIFICATION_TYPE_MACRO(NOTIFICATION_CTP_, MQDC_RECEIVE_DATA)


  //MQ
  ITEM_NOTIFICATION_TYPE_MACRO(NOTIFICATION_CTP_, MQ_MQLEVEL_INFO)
  ITEM_NOTIFICATION_TYPE_MACRO(NOTIFICATION_CTP_, MQ_MQLEVEL_INFO_TRADE_USE)
  ITEM_NOTIFICATION_TYPE_MACRO(NOTIFICATION_CTP_, MQ_BASIC_INFO)
  ITEM_NOTIFICATION_TYPE_MACRO(NOTIFICATION_CTP_, MQ_BASIC_INFO_LITE)

  //tos
    ITEM_NOTIFICATION_TYPE_MACRO(NOTIFICATION_CTP_, TOS_RECEIVE_DATA)
    ITEM_NOTIFICATION_TYPE_MACRO(NOTIFICATION_CTP_, TOS_ORDER_INSERT)

    //console
    ITEM_NOTIFICATION_TYPE_MACRO(NOTIFICATION_CTP_, CONSOLE_COMMAND)

  //other
  ITEM_NOTIFICATION_TYPE_MACRO(NOTIFICATION_CTP_, TORMSM_STATE_CHANGE_NODEAL)

//performance
ITEM_NOTIFICATION_TYPE_MACRO(NOTIFICATION_CTP_, PERFORMANCE_MEMORY_DB_SAVE_MQ)


  //new archtecture
  //lsm
  ITEM_NOTIFICATION_TYPE_MACRO(NOTIFICATION_CTP_, LSM_CONNECTED)
  ITEM_NOTIFICATION_TYPE_MACRO(NOTIFICATION_CTP_, LSM_DISCONNECT)
  ITEM_NOTIFICATION_TYPE_MACRO(NOTIFICATION_CTP_, LSM_DISCONNECT_4_SHOW)
  //用户广播信息给ui显示=
  ITEM_NOTIFICATION_TYPE_MACRO(NOTIFICATION_CTP_, LSM_LOGIN_RSP)
  //用于广播登录成功，模块处理相关逻辑，比如发SettlementInfoConfirm=
  ITEM_NOTIFICATION_TYPE_MACRO(NOTIFICATION_CTP_, LSM_LOGIN_SUCCESS)
  ITEM_NOTIFICATION_TYPE_MACRO(NOTIFICATION_CTP_, LSM_LOGIN_FAILED)
  ITEM_NOTIFICATION_TYPE_MACRO(NOTIFICATION_CTP_, LSM_LOGOUT_SUCCESS)
  ITEM_NOTIFICATION_TYPE_MACRO(NOTIFICATION_CTP_, LSM_LOGOUT_RSP)
  ITEM_NOTIFICATION_TYPE_MACRO(NOTIFICATION_CTP_, LSM_STATE_CHANGE)
  ITEM_NOTIFICATION_TYPE_MACRO(NOTIFICATION_CTP_, LSM_STATE_CHANGE_DEAL)
  ITEM_NOTIFICATION_TYPE_MACRO(NOTIFICATION_CTP_, LSM_STATE_CHANGE_NODEAL)
  //ITEM_NOTIFICATION_TYPE_MACRO(NOTIFICATION_CTP_, LSM_NETWORK)
  ITEM_NOTIFICATION_TYPE_MACRO(NOTIFICATION_CTP_, LSM_TIMER)



  //MS
  ITEM_NOTIFICATION_TYPE_MACRO(NOTIFICATION_CTP_, MS_ORDER_ACTION)  
  ITEM_NOTIFICATION_TYPE_MACRO(NOTIFICATION_CTP_, MS_ORDER_ACTION_NEW)  
  ITEM_NOTIFICATION_TYPE_MACRO(NOTIFICATION_CTP_, MS_ORDER_ACTION_TEST)  
  ITEM_NOTIFICATION_TYPE_MACRO(NOTIFICATION_CTP_, MS_ACTION_INFO_FROM_R)  

  ITEM_NOTIFICATION_TYPE_MACRO(NOTIFICATION_CTP_, PARSERED_RCMD)  

  //MESM
  ITEM_NOTIFICATION_TYPE_MACRO(NOTIFICATION_CTP_, MESM_STATE_CHANGE)
  ITEM_NOTIFICATION_TYPE_MACRO(NOTIFICATION_CTP_, MESM_STATE_CHANGE_DEAL)
  ITEM_NOTIFICATION_TYPE_MACRO(NOTIFICATION_CTP_, MESM_TIMER)
  ITEM_NOTIFICATION_TYPE_MACRO(NOTIFICATION_CTP_, MESM_ACTION)
  ITEM_NOTIFICATION_TYPE_MACRO(NOTIFICATION_CTP_, MESM_TRADE_SUCCESS)
  ITEM_NOTIFICATION_TYPE_MACRO(NOTIFICATION_CTP_, MESM_TRADE_FAILED)
  ITEM_NOTIFICATION_TYPE_MACRO(NOTIFICATION_CTP_, MESM_TRADE_STARTED)
  ITEM_NOTIFICATION_TYPE_MACRO(NOTIFICATION_CTP_, MESM_RECEIVE_DATA)
  ITEM_NOTIFICATION_TYPE_MACRO(NOTIFICATION_CTP_, MESM_SEND_DATA)
  //ITEM_NOTIFICATION_TYPE_MACRO(NOTIFICATION_CTP_, LSM_STATE_CHANGE_NODEAL)


  //TSM
ITEM_NOTIFICATION_TYPE_MACRO(NOTIFICATION_CTP_, TSM_STATE_CHANGE_DEAL)
ITEM_NOTIFICATION_TYPE_MACRO(NOTIFICATION_CTP_, TSM_STATE_CHANGE)
ITEM_NOTIFICATION_TYPE_MACRO(NOTIFICATION_CTP_, TSM_ACTION)


ITEM_NOTIFICATION_TYPE_MACRO(NOTIFICATION_CTP_, INIT_FINISHED)

//R
ITEM_NOTIFICATION_TYPE_MACRO(NOTIFICATION_CTP_, R_ACTION)
  //MESSAGE_VALUE__SM_STATE_NORMAL_MSG,
  TAIL_NOTIFICATION_TYPE_MACRO
END_NOTIFICATION_TYPE_MACOR



