# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cc_comunication.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cc_comunication.proto',
  package='ctp.c2c',
  serialized_pb='\n\x15\x63\x63_comunication.proto\x12\x07\x63tp.c2c\"&\n\x07\x43ommand\x12\x0b\n\x03\x63md\x18\x01 \x02(\t\x12\x0e\n\x06params\x18\x02 \x01(\t')




_COMMAND = _descriptor.Descriptor(
  name='Command',
  full_name='ctp.c2c.Command',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cmd', full_name='ctp.c2c.Command.cmd', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='params', full_name='ctp.c2c.Command.params', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=34,
  serialized_end=72,
)

DESCRIPTOR.message_types_by_name['Command'] = _COMMAND

class Command(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _COMMAND

  # @@protoc_insertion_point(class_scope:ctp.c2c.Command)


# @@protoc_insertion_point(module_scope)
