# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: guard_comunication.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='guard_comunication.proto',
  package='ctp.guard',
  serialized_pb='\n\x18guard_comunication.proto\x12\tctp.guard\"\x1f\n\tReportPid\x12\x12\n\nprocess_id\x18\x01 \x02(\x05\"C\n\tCommonCmd\x12\x0c\n\x04str1\x18\x01 \x02(\t\x12\x0c\n\x04str2\x18\x02 \x02(\t\x12\x0c\n\x04str3\x18\x03 \x02(\t\x12\x0c\n\x04str4\x18\x04 \x02(\t')




_REPORTPID = _descriptor.Descriptor(
  name='ReportPid',
  full_name='ctp.guard.ReportPid',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='process_id', full_name='ctp.guard.ReportPid.process_id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=39,
  serialized_end=70,
)


_COMMONCMD = _descriptor.Descriptor(
  name='CommonCmd',
  full_name='ctp.guard.CommonCmd',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='str1', full_name='ctp.guard.CommonCmd.str1', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='str2', full_name='ctp.guard.CommonCmd.str2', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='str3', full_name='ctp.guard.CommonCmd.str3', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='str4', full_name='ctp.guard.CommonCmd.str4', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=72,
  serialized_end=139,
)

DESCRIPTOR.message_types_by_name['ReportPid'] = _REPORTPID
DESCRIPTOR.message_types_by_name['CommonCmd'] = _COMMONCMD

class ReportPid(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REPORTPID

  # @@protoc_insertion_point(class_scope:ctp.guard.ReportPid)

class CommonCmd(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _COMMONCMD

  # @@protoc_insertion_point(class_scope:ctp.guard.CommonCmd)


# @@protoc_insertion_point(module_scope)
